"""Sync models with existing database schema

Revision ID: 41ee2f43d014
Revises: 
Create Date: 2025-11-14 16:30:12.749866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41ee2f43d014'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_backup_clients')
    op.drop_table('_backup_usecases')
    op.drop_index(op.f('idx_entity_notes_created_at'), table_name='entity_notes')
    op.drop_index(op.f('idx_entity_notes_created_by'), table_name='entity_notes')
    op.drop_index(op.f('idx_entity_notes_entity'), table_name='entity_notes')
    op.drop_table('entity_notes')
    op.drop_index(op.f('idx_report_snapshots_generated_by'), table_name='report_snapshots')
    op.drop_index(op.f('idx_report_snapshots_type'), table_name='report_snapshots')
    op.drop_table('report_snapshots')
    op.drop_table('_backup_projects')
    op.drop_table('_backup_subtasks')
    op.drop_table('_backup_bugs')
    op.drop_table('_backup_programs')
    op.drop_table('_backup_tasks')
    op.drop_index(op.f('idx_entity_history_changed_at'), table_name='entity_history')
    op.drop_index(op.f('idx_entity_history_changed_by'), table_name='entity_history')
    op.drop_index(op.f('idx_entity_history_entity'), table_name='entity_history')
    op.drop_table('entity_history')
    op.drop_table('_backup_user_stories')
    op.drop_table('_backup_users')
    op.drop_table('_backup_phases')
    op.drop_index(op.f('idx_company_settings_client_id'), table_name='company_settings')
    op.drop_index(op.f('idx_company_settings_is_active'), table_name='company_settings')
    op.drop_table('company_settings')
    op.add_column('audit_logs', sa.Column('project_id', sa.String(length=20), nullable=True))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_client_id'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='audit_logs')
    op.drop_constraint(op.f('audit_logs_client_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'projects', ['project_id'], ['id'])
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Immutable audit log table. Records should never be updated or deleted. Retention policy: 7 years minimum.',
        schema=None
    )
    op.add_column('bugs', sa.Column('user_story_id', sa.String(length=20), nullable=True))
    op.add_column('bugs', sa.Column('task_id', sa.String(length=20), nullable=True))
    op.add_column('bugs', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('bugs', sa.Column('environment', sa.String(length=100), nullable=True))
    op.add_column('bugs', sa.Column('steps_to_reproduce', sa.Text(), nullable=True))
    op.add_column('bugs', sa.Column('expected_behavior', sa.Text(), nullable=True))
    op.add_column('bugs', sa.Column('actual_behavior', sa.Text(), nullable=True))
    op.alter_column('bugs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('bugs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_bugs_assigned_to'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_entity'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_is_deleted'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_priority'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_reported_by'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_severity'), table_name='bugs')
    op.drop_index(op.f('idx_bugs_status'), table_name='bugs')
    op.drop_constraint(op.f('bugs_updated_by_fkey'), 'bugs', type_='foreignkey')
    op.drop_constraint(op.f('bugs_created_by_fkey'), 'bugs', type_='foreignkey')
    op.drop_constraint(op.f('bugs_assigned_to_fkey'), 'bugs', type_='foreignkey')
    op.create_foreign_key(None, 'bugs', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'bugs', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'bugs', 'user_stories', ['user_story_id'], ['id'])
    op.drop_column('bugs', 'long_description')
    op.drop_column('bugs', 'created_by')
    op.drop_column('bugs', 'updated_by')
    op.drop_column('bugs', 'entity_id')
    op.drop_column('bugs', 'resolution_notes')
    op.drop_column('bugs', 'short_description')
    op.drop_column('bugs', 'entity_type')
    op.drop_column('bugs', 'is_deleted')
    op.alter_column('clients', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clients', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('clients', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('clients', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_clients_is_deleted'), table_name='clients')
    op.alter_column('commits', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('commits', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('idx_commits_hash'), table_name='commits')
    op.drop_index(op.f('idx_commits_repository'), table_name='commits')
    op.drop_index(op.f('idx_commits_task_id'), table_name='commits')
    op.create_foreign_key(None, 'commits', 'tasks', ['task_id'], ['id'])
    op.alter_column('dependencies', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dependencies', 'entity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dependencies', 'depends_on_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_dependencies_depends_on'), table_name='dependencies')
    op.drop_index(op.f('idx_dependencies_entity'), table_name='dependencies')
    op.alter_column('documentation', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('documentation', 'entity_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('documentation', 'format',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('documentation', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('documentation', 'author_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_documentation_author_id'), table_name='documentation')
    op.drop_index(op.f('idx_documentation_entity'), table_name='documentation')
    op.create_foreign_key(None, 'documentation', 'users', ['author_id'], ['id'])
    op.add_column('phases', sa.Column('order', sa.Integer(), nullable=False))
    op.alter_column('phases', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phases', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('phases', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('phases', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('phases', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phases', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('phases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('phases', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('phases', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_phases_display_order'), table_name='phases')
    op.drop_index(op.f('idx_phases_is_active'), table_name='phases')
    op.drop_index(op.f('idx_phases_is_deleted'), table_name='phases')
    op.drop_constraint(op.f('phases_created_by_fkey'), 'phases', type_='foreignkey')
    op.drop_constraint(op.f('phases_updated_by_fkey'), 'phases', type_='foreignkey')
    op.drop_column('phases', 'display_order')
    op.alter_column('programs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('programs', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('programs', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('programs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('programs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('programs', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('programs', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_programs_client_id'), table_name='programs')
    op.drop_index(op.f('idx_programs_is_deleted'), table_name='programs')
    op.drop_index(op.f('idx_programs_status'), table_name='programs')
    op.drop_constraint(op.f('programs_updated_by_fkey'), 'programs', type_='foreignkey')
    op.drop_constraint(op.f('programs_client_id_fkey'), 'programs', type_='foreignkey')
    op.drop_constraint(op.f('programs_created_by_fkey'), 'programs', type_='foreignkey')
    op.create_foreign_key(None, 'programs', 'clients', ['client_id'], ['id'])
    op.alter_column('projects', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('projects', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('projects', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('idx_projects_program_id'), table_name='projects')
    op.drop_index(op.f('idx_projects_status'), table_name='projects')
    op.drop_constraint(op.f('projects_updated_by_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_program_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'programs', ['program_id'], ['id'])
    op.alter_column('pull_requests', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('pull_requests', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('pull_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_pull_requests_status'), table_name='pull_requests')
    op.drop_index(op.f('idx_pull_requests_task_id'), table_name='pull_requests')
    op.create_foreign_key(None, 'pull_requests', 'tasks', ['task_id'], ['id'])
    op.alter_column('sprint_tasks', 'sprint_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sprint_tasks', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('idx_sprint_tasks_sprint_id'), table_name='sprint_tasks')
    op.drop_index(op.f('idx_sprint_tasks_task_id'), table_name='sprint_tasks')
    op.drop_constraint(op.f('sprint_tasks_sprint_id_fkey'), 'sprint_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'sprint_tasks', 'sprints', ['sprint_id'], ['id'])
    op.create_foreign_key(None, 'sprint_tasks', 'tasks', ['task_id'], ['id'])
    op.alter_column('sprints', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sprints', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sprints', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_sprints_dates'), table_name='sprints')
    op.drop_index(op.f('idx_sprints_project_id'), table_name='sprints')
    op.drop_index(op.f('idx_sprints_status'), table_name='sprints')
    op.create_foreign_key(None, 'sprints', 'projects', ['project_id'], ['id'])
    op.add_column('subtasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('subtasks', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subtasks', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('subtasks', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('subtasks', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('subtasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('subtasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('subtasks', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('subtasks', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_subtasks_assigned_to'), table_name='subtasks')
    op.drop_index(op.f('idx_subtasks_is_deleted'), table_name='subtasks')
    op.drop_index(op.f('idx_subtasks_phase_id'), table_name='subtasks')
    op.drop_index(op.f('idx_subtasks_status'), table_name='subtasks')
    op.drop_index(op.f('idx_subtasks_task_id'), table_name='subtasks')
    op.drop_constraint(op.f('subtasks_created_by_fkey'), 'subtasks', type_='foreignkey')
    op.drop_constraint(op.f('subtasks_task_id_fkey'), 'subtasks', type_='foreignkey')
    op.drop_constraint(op.f('subtasks_assigned_to_fkey'), 'subtasks', type_='foreignkey')
    op.drop_constraint(op.f('subtasks_updated_by_fkey'), 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'subtasks', 'users', ['assigned_to'], ['id'])
    op.drop_table_comment(
        'subtasks',
        existing_comment='Subtasks can only be created under Tasks, not under other Subtasks. This constraint is enforced at the application level.',
        schema=None
    )
    op.drop_column('subtasks', 'name')
    op.drop_column('subtasks', 'estimated_hours')
    op.drop_column('subtasks', 'actual_hours')
    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('tasks', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tasks', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('tasks', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tasks', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_assigned_to'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_phase_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_status'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_story_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_story_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_updated_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_created_by_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_assigned_to_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'user_stories', ['user_story_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.drop_column('tasks', 'name')
    op.alter_column('usecases', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('usecases', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('usecases', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('usecases', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usecases', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('usecases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('usecases', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usecases', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_usecases_is_deleted'), table_name='usecases')
    op.drop_index(op.f('idx_usecases_project_id'), table_name='usecases')
    op.drop_index(op.f('idx_usecases_status'), table_name='usecases')
    op.drop_constraint(op.f('usecases_project_id_fkey'), 'usecases', type_='foreignkey')
    op.drop_constraint(op.f('usecases_created_by_fkey'), 'usecases', type_='foreignkey')
    op.drop_constraint(op.f('usecases_updated_by_fkey'), 'usecases', type_='foreignkey')
    op.create_foreign_key(None, 'usecases', 'projects', ['project_id'], ['id'])
    op.add_column('user_stories', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('user_stories', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_stories', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('user_stories', 'long_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('user_stories', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_stories', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('user_stories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('user_stories', 'created_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('user_stories', 'updated_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_user_stories_is_deleted'), table_name='user_stories')
    op.drop_index(op.f('idx_user_stories_status'), table_name='user_stories')
    op.drop_index(op.f('idx_user_stories_usecase_id'), table_name='user_stories')
    op.drop_constraint(op.f('user_stories_created_by_fkey'), 'user_stories', type_='foreignkey')
    op.drop_constraint(op.f('user_stories_updated_by_fkey'), 'user_stories', type_='foreignkey')
    op.drop_constraint(op.f('user_stories_usecase_id_fkey'), 'user_stories', type_='foreignkey')
    op.create_foreign_key(None, 'user_stories', 'usecases', ['usecase_id'], ['id'])
    op.drop_column('user_stories', 'name')
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='User role determines permissions: Admin (full access), Architect (programs/projects/usecases/stories), Designer (usecases/stories), Developer (tasks/subtasks/bugs), Tester (bugs)',
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_users_client_id'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_role'), table_name='users')
    op.drop_index(op.f('idx_users_view_preferences'), table_name='users', postgresql_using='gin')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('users_client_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    op.drop_column('users', 'view_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('view_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"defaultView": "tile", "entityViews": {"bugs": "list", "tasks": "list", "clients": "tile", "programs": "tile", "projects": "tile", "subtasks": "list", "usecases": "list", "userstories": "list"}}\'::jsonb'), autoincrement=False, nullable=True, comment='User UI preferences stored as JSON. Includes defaultView (tile/list) and per-entity view preferences. Example: {"defaultView": "tile", "entityViews": {"clients": "tile", "projects": "list"}}'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_client_id_fkey'), 'users', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_view_preferences'), 'users', ['view_preferences'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_client_id'), 'users', ['client_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('users', 'theme',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'snow'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='User role determines permissions: Admin (full access), Architect (programs/projects/usecases/stories), Designer (usecases/stories), Developer (tasks/subtasks/bugs), Tester (bugs)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('USR'::text, 'users_id_seq'::text)"),
               existing_nullable=False)
    op.add_column('user_stories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_stories', type_='foreignkey')
    op.create_foreign_key(op.f('user_stories_usecase_id_fkey'), 'user_stories', 'usecases', ['usecase_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_stories_updated_by_fkey'), 'user_stories', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('user_stories_created_by_fkey'), 'user_stories', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_user_stories_usecase_id'), 'user_stories', ['usecase_id'], unique=False)
    op.create_index(op.f('idx_user_stories_status'), 'user_stories', ['status'], unique=False)
    op.create_index(op.f('idx_user_stories_is_deleted'), 'user_stories', ['is_deleted'], unique=False)
    op.alter_column('user_stories', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('user_stories', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('user_stories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('user_stories', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Backlog'::character varying"),
               existing_nullable=True)
    op.alter_column('user_stories', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Medium'::character varying"),
               existing_nullable=True)
    op.alter_column('user_stories', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('user_stories', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('user_stories', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('UST'::text, 'user_stories_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('user_stories', 'title')
    op.drop_constraint(None, 'usecases', type_='foreignkey')
    op.create_foreign_key(op.f('usecases_updated_by_fkey'), 'usecases', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('usecases_created_by_fkey'), 'usecases', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('usecases_project_id_fkey'), 'usecases', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_usecases_status'), 'usecases', ['status'], unique=False)
    op.create_index(op.f('idx_usecases_project_id'), 'usecases', ['project_id'], unique=False)
    op.create_index(op.f('idx_usecases_is_deleted'), 'usecases', ['is_deleted'], unique=False)
    op.alter_column('usecases', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('usecases', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('usecases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('usecases', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Draft'::character varying"),
               existing_nullable=True)
    op.alter_column('usecases', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Medium'::character varying"),
               existing_nullable=True)
    op.alter_column('usecases', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('usecases', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('usecases', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('USC'::text, 'usecases_id_seq'::text)"),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_assigned_to_fkey'), 'tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_created_by_fkey'), 'tasks', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('tasks_updated_by_fkey'), 'tasks', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('tasks_user_story_id_fkey'), 'tasks', 'user_stories', ['user_story_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_tasks_user_story_id'), 'tasks', ['user_story_id'], unique=False)
    op.create_index(op.f('idx_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('idx_tasks_phase_id'), 'tasks', ['phase_id'], unique=False)
    op.create_index(op.f('idx_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.alter_column('tasks', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tasks', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Medium'::character varying"),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'To Do'::character varying"),
               existing_nullable=True)
    op.alter_column('tasks', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('tasks', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('tasks', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('TSK'::text, 'tasks_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('tasks', 'title')
    op.add_column('subtasks', sa.Column('actual_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('subtasks', sa.Column('estimated_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('subtasks', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_table_comment(
        'subtasks',
        'Subtasks can only be created under Tasks, not under other Subtasks. This constraint is enforced at the application level.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_updated_by_fkey'), 'subtasks', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('subtasks_assigned_to_fkey'), 'subtasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('subtasks_task_id_fkey'), 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subtasks_created_by_fkey'), 'subtasks', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.create_index(op.f('idx_subtasks_status'), 'subtasks', ['status'], unique=False)
    op.create_index(op.f('idx_subtasks_phase_id'), 'subtasks', ['phase_id'], unique=False)
    op.create_index(op.f('idx_subtasks_is_deleted'), 'subtasks', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_subtasks_assigned_to'), 'subtasks', ['assigned_to'], unique=False)
    op.alter_column('subtasks', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('subtasks', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('subtasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('subtasks', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'To Do'::character varying"),
               existing_nullable=True)
    op.alter_column('subtasks', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('subtasks', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('subtasks', 'phase_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('subtasks', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('SUB'::text, 'subtasks_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('subtasks', 'title')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_index(op.f('idx_sprints_status'), 'sprints', ['status'], unique=False)
    op.create_index(op.f('idx_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('idx_sprints_dates'), 'sprints', ['start_date', 'end_date'], unique=False)
    op.alter_column('sprints', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Planning'::character varying"),
               existing_nullable=True)
    op.alter_column('sprints', 'project_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sprints', 'id',
               existing_type=sa.String(length=20),
               server_default=sa.text('uuid_generate_v4()'),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'sprint_tasks', type_='foreignkey')
    op.drop_constraint(None, 'sprint_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('sprint_tasks_sprint_id_fkey'), 'sprint_tasks', 'sprints', ['sprint_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_sprint_tasks_task_id'), 'sprint_tasks', ['task_id'], unique=False)
    op.create_index(op.f('idx_sprint_tasks_sprint_id'), 'sprint_tasks', ['sprint_id'], unique=False)
    op.alter_column('sprint_tasks', 'task_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('sprint_tasks', 'sprint_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.create_index(op.f('idx_pull_requests_task_id'), 'pull_requests', ['task_id'], unique=False)
    op.create_index(op.f('idx_pull_requests_status'), 'pull_requests', ['status'], unique=False)
    op.alter_column('pull_requests', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'open'::character varying"),
               existing_nullable=True)
    op.alter_column('pull_requests', 'task_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('pull_requests', 'id',
               existing_type=sa.String(length=20),
               server_default=sa.text('uuid_generate_v4()'),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('projects_program_id_fkey'), 'projects', 'programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('projects_updated_by_fkey'), 'projects', 'users', ['updated_by'], ['id'])
    op.create_index(op.f('idx_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('idx_projects_program_id'), 'projects', ['program_id'], unique=False)
    op.create_index(op.f('idx_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.alter_column('projects', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Planning'::character varying"),
               existing_nullable=True)
    op.alter_column('projects', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('projects', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('PRJ'::text, 'projects_id_seq'::text)"),
               existing_nullable=False)
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.create_foreign_key(op.f('programs_created_by_fkey'), 'programs', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('programs_client_id_fkey'), 'programs', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('programs_updated_by_fkey'), 'programs', 'users', ['updated_by'], ['id'])
    op.create_index(op.f('idx_programs_status'), 'programs', ['status'], unique=False)
    op.create_index(op.f('idx_programs_is_deleted'), 'programs', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_programs_client_id'), 'programs', ['client_id'], unique=False)
    op.alter_column('programs', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('programs', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('programs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('programs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Planning'::character varying"),
               existing_nullable=True)
    op.alter_column('programs', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('programs', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('programs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('PRG'::text, 'programs_id_seq'::text)"),
               existing_nullable=False)
    op.add_column('phases', sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('phases_updated_by_fkey'), 'phases', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('phases_created_by_fkey'), 'phases', 'users', ['created_by'], ['id'])
    op.create_index(op.f('idx_phases_is_deleted'), 'phases', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_phases_is_active'), 'phases', ['is_active'], unique=False)
    op.create_index(op.f('idx_phases_display_order'), 'phases', ['display_order'], unique=False)
    op.alter_column('phases', 'updated_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('phases', 'created_by',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('phases', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('phases', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('phases', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'#4A90E2'::character varying"),
               existing_nullable=False)
    op.alter_column('phases', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('phases', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('phases', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('phases', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('PHS'::text, 'phases_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('phases', 'order')
    op.drop_constraint(None, 'documentation', type_='foreignkey')
    op.create_index(op.f('idx_documentation_entity'), 'documentation', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_documentation_author_id'), 'documentation', ['author_id'], unique=False)
    op.alter_column('documentation', 'author_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('documentation', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('documentation', 'format',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'markdown'::character varying"),
               existing_nullable=True)
    op.alter_column('documentation', 'entity_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('documentation', 'id',
               existing_type=sa.String(length=20),
               server_default=sa.text('uuid_generate_v4()'),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('idx_dependencies_entity'), 'dependencies', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_dependencies_depends_on'), 'dependencies', ['depends_on_type', 'depends_on_id'], unique=False)
    op.alter_column('dependencies', 'dependency_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'finish_to_start'::character varying"),
               existing_nullable=True)
    op.alter_column('dependencies', 'depends_on_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('dependencies', 'entity_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('dependencies', 'id',
               existing_type=sa.String(length=20),
               server_default=sa.text('uuid_generate_v4()'),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.create_index(op.f('idx_commits_task_id'), 'commits', ['task_id'], unique=False)
    op.create_index(op.f('idx_commits_repository'), 'commits', ['repository'], unique=False)
    op.create_index(op.f('idx_commits_hash'), 'commits', ['commit_hash'], unique=False)
    op.alter_column('commits', 'task_id',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('commits', 'id',
               existing_type=sa.String(length=20),
               server_default=sa.text('uuid_generate_v4()'),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('idx_clients_is_deleted'), 'clients', ['is_deleted'], unique=False)
    op.alter_column('clients', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('clients', 'long_description',
               existing_type=sa.TEXT(),
               comment='Detailed description with unlimited length for full entity view',
               existing_nullable=True)
    op.alter_column('clients', 'short_description',
               existing_type=sa.VARCHAR(length=500),
               comment='Brief summary (max 500 chars) displayed in lists and cards',
               existing_nullable=True)
    op.alter_column('clients', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('CLI'::text, 'clients_id_seq'::text)"),
               existing_nullable=False)
    op.add_column('bugs', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('bugs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('bugs', sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Brief summary (max 500 chars) displayed in lists and cards'))
    op.add_column('bugs', sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bugs', sa.Column('entity_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bugs', sa.Column('updated_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('bugs', sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('bugs', sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed description with unlimited length for full entity view'))
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.create_foreign_key(op.f('bugs_assigned_to_fkey'), 'bugs', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('bugs_created_by_fkey'), 'bugs', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('bugs_updated_by_fkey'), 'bugs', 'users', ['updated_by'], ['id'])
    op.create_index(op.f('idx_bugs_status'), 'bugs', ['status'], unique=False)
    op.create_index(op.f('idx_bugs_severity'), 'bugs', ['severity'], unique=False)
    op.create_index(op.f('idx_bugs_reported_by'), 'bugs', ['reported_by'], unique=False)
    op.create_index(op.f('idx_bugs_priority'), 'bugs', ['priority'], unique=False)
    op.create_index(op.f('idx_bugs_is_deleted'), 'bugs', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_bugs_entity'), 'bugs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_bugs_assigned_to'), 'bugs', ['assigned_to'], unique=False)
    op.alter_column('bugs', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'New'::character varying"),
               existing_nullable=True)
    op.alter_column('bugs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('BUG'::text, 'bugs_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('bugs', 'actual_behavior')
    op.drop_column('bugs', 'expected_behavior')
    op.drop_column('bugs', 'steps_to_reproduce')
    op.drop_column('bugs', 'environment')
    op.drop_column('bugs', 'description')
    op.drop_column('bugs', 'task_id')
    op.drop_column('bugs', 'user_story_id')
    op.create_table_comment(
        'audit_logs',
        'Immutable audit log table. Records should never be updated or deleted. Retention policy: 7 years minimum.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_user_id_fkey'), 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('audit_logs_client_id_fkey'), 'audit_logs', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_client_id'), 'audit_logs', ['client_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("generate_string_id('AUD'::text, 'audit_logs_id_seq'::text)"),
               existing_nullable=False)
    op.drop_column('audit_logs', 'project_id')
    op.create_table('company_settings',
    sa.Column('id', sa.VARCHAR(length=20), server_default=sa.text("generate_string_id('CMP'::text, 'company_settings_id_seq'::text)"), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='URL to company logo image (e.g., S3, CDN, or local path)'),
    sa.Column('company_logo_data', sa.TEXT(), autoincrement=False, nullable=True, comment='Base64 encoded logo image data for embedded storage'),
    sa.Column('primary_color', sa.VARCHAR(length=7), server_default=sa.text("'#4A90E2'::character varying"), autoincrement=False, nullable=True, comment='Primary brand color in hex format (e.g., #4A90E2)'),
    sa.Column('secondary_color', sa.VARCHAR(length=7), server_default=sa.text("'#2C3E50'::character varying"), autoincrement=False, nullable=True, comment='Secondary brand color in hex format'),
    sa.Column('report_header_text', sa.TEXT(), autoincrement=False, nullable=True, comment='Custom text to display in report headers'),
    sa.Column('report_footer_text', sa.TEXT(), autoincrement=False, nullable=True, comment='Custom text to display in report footers (e.g., copyright, contact info)'),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=True, comment='Default timezone for the company (e.g., America/New_York, Asia/Kolkata)'),
    sa.Column('date_format', sa.VARCHAR(length=20), server_default=sa.text("'YYYY-MM-DD'::character varying"), autoincrement=False, nullable=True, comment='Preferred date format (e.g., YYYY-MM-DD, DD/MM/YYYY, MM/DD/YYYY)'),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True, comment='Default currency code (ISO 4217, e.g., USD, EUR, INR)'),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('company_settings_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('company_settings_created_by_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('company_settings_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_settings_pkey')),
    sa.UniqueConstraint('client_id', name=op.f('company_settings_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Company branding and settings per client. Only one row per client. Logo can be stored as URL or base64 data.'
    )
    op.create_index(op.f('idx_company_settings_is_active'), 'company_settings', ['is_active'], unique=False)
    op.create_index(op.f('idx_company_settings_client_id'), 'company_settings', ['client_id'], unique=False)
    op.create_table('_backup_phases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_user_stories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usecase_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acceptance_criteria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('story_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('entity_history',
    sa.Column('id', sa.VARCHAR(length=20), server_default=sa.text("generate_string_id('HIS'::text, 'entity_history_id_seq'::text)"), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('entity_history_changed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_history_pkey')),
    comment='Field-level change tracking for all entities. Provides detailed audit trail of what changed, when, and by whom.'
    )
    op.create_index(op.f('idx_entity_history_entity'), 'entity_history', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_entity_history_changed_by'), 'entity_history', ['changed_by'], unique=False)
    op.create_index(op.f('idx_entity_history_changed_at'), 'entity_history', ['changed_at'], unique=False)
    op.create_table('_backup_tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_story_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estimated_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('actual_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phase_id', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_programs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_bugs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_story_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reported_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('environment', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('steps_to_reproduce', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expected_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actual_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_subtasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('phase_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estimated_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('actual_hours', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_projects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('program_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('repository_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('report_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('report_snapshots_pkey'))
    )
    op.create_index(op.f('idx_report_snapshots_type'), 'report_snapshots', ['report_type'], unique=False)
    op.create_index(op.f('idx_report_snapshots_generated_by'), 'report_snapshots', ['generated_by'], unique=False)
    op.create_table('entity_notes',
    sa.Column('id', sa.VARCHAR(length=20), server_default=sa.text("generate_string_id('NOT'::text, 'entity_notes_id_seq'::text)"), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("entity_type::text = ANY (ARRAY['Client'::character varying, 'Program'::character varying, 'Project'::character varying, 'UseCase'::character varying, 'UserStory'::character varying, 'Task'::character varying, 'Subtask'::character varying, 'Bug'::character varying]::text[])", name=op.f('entity_notes_entity_type_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('entity_notes_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('entity_notes_pkey')),
    comment='Immutable notes table. Notes can be attached to any entity. Once created, notes cannot be edited or deleted. Display in reverse chronological order on UI.'
    )
    op.create_index(op.f('idx_entity_notes_entity'), 'entity_notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_entity_notes_created_by'), 'entity_notes', ['created_by'], unique=False)
    op.create_index(op.f('idx_entity_notes_created_at'), 'entity_notes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('_backup_usecases',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_table('_backup_clients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
